default: &default
  adapter: postgresql
  # encoding: unicode
  endcoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: badranker_development

test:
  <<: *default
  database: badranker_test

production:
  <<: *default
  database: badranker_production
  # username: <%= ENV["POSTGRES_USER"] %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>

